### ISSUE TITLE
RSI is wrong?

### ISSUE THREAD

**Issue by sithulol** [AbenezerMamo/crypto-signal#1]
seems to me the RSI displayed is very wrong from bittrex charts. I changed unit to thirtyMin to match it but its still off.

**Comment by hanyoon93** [comment]
Getting the same problem here as well. RSI way off.

**Comment by AbenezerMamo** [comment]
Looking into this right now

**Comment by AbenezerMamo** [comment]
The RSI itself should only be off by 1-3 points and no more. This is due to the fact that I didn't smooth out the RS before calculating the RSI. A fix for this will be coming shortly

**Comment by AbenezerMamo** [comment]
Update: Implemented smoothed RS calculations but it's still a work in progress. Calculating this from scratch has its own set of challenges it seems haha! But not impossible. It's relatively accurate but I'll be working towards making it mirror the value you get from Bittrex Studies
