### ISSUE TITLE
Breakout algorithm

### ISSUE THREAD

**Issue by behl1** [AbenezerMamo/crypto-signal#10]
Hey,
Great job on the signal. How sure are you of your breakout algo? Seems really simplistic i.e. does not take into consideration channels, triangles, etc. Do you see this being a viable signal? Sorry for the noobish questions.

**Comment by AbenezerMamo** [comment]
I would recommend using the Ichomoku cloud to help you find cross overs since it takes into account support and resistance lines. 

The breakout algorithm is simply intended to tell you when something is going to have a really really giant green candle ;) aka when people are fomo buying.

**Comment by pdonorio** [comment]
Hi @AbenezerMamo, would you mind helping with that? I can't find any "Ichomoku" name in the whole repo except for the README. Maybe it's just a noobie question.

**Comment by pdonorio** [comment]
Alright, totally noobie :D 

the cloud is the space between spanA and spanB which are functions available in the app.

**Comment by behl1** [comment]
Hey @AbenezerMamo,
Sorry for the late reply and thanks for the tip on ichimoku. Care to share any stats on the success of some algos? Demo account stats of course :)
