### ISSUE TITLE
Docker for Windows

### ISSUE THREAD

**Issue by Bird-NZ** [AbenezerMamo/crypto-signal#100]
I'm trying to use Docker for windows for this project.
I am stuck as I do not know how to generate the env file to be able to build the docker image hence I'm getting the error below:
--------------
PS C:\docker\crypto-signal-master> docker run -it --rm --env-file .env crypto-signal
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: open .env: The system cannot find the file specified.
-----------
Can a few simple steps be written to be able to compile a docker image, including how to generate the env file needed.

As background docker version I'm using is:
PS C:\docker\crypto-signal-master> docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by shads2** [comment]
A lot of the answers you are looking for are probably already covered here: https://github.com/AbenezerMamo/crypto-signal/issues/60

The short answer is you need to use the CLI (powershell or dos prompt) or a text editor like sublime, atom, visual studio code. Basically anything that can create files that is _not_ windows explorer will allow you to create the .env file.

**Comment by Bird-NZ** [comment]
Thx, yes using Atom to create an empty file called ".env" solved this. Build now completes. 

BUT....(there's always a but)
When I run: "docker-compose run app" I get:

Traceback (most recent call last):
  File "app.py", line 11, in <module>
    from behaviour import Behaviour
  File "/app/behaviour.py", line 8, in <modul
    from analysis import StrategyAnalyzer
  File "/app/analysis.py", line 8, in <module
    from talib import abstract
ModuleNotFoundError: No module named 'talib'

**Comment by shads2** [comment]
Well... that is a new one, when you run `make build` are there any errors in the output about TA lib?

**Comment by shads2** [comment]
In the previous issue I referenced earlier https://github.com/AbenezerMamo/crypto-signal/issues/60 it mentions that you need http://www.mingw.org/wiki/msys. You can alternatively just run `docker build -t crypto-signal .`

**Comment by Bird-NZ** [comment]
Thx, yes I read #60 and have MSYS installed. I'll try 'docker build -t crypto-signal .' tonight. Thx again for your support.

**Comment by shads2** [comment]
No problem!

**Comment by Bird-NZ** [comment]
Hi here is the output form:
docker build -t crypto-signal .

followed by:
docker-compose run app

----------------------
PS C:\Users\matgb\OneDrive\Crypto\Bot\crypto-signal-master\crypto-signal-master> docker build -t crypto-signal .
Sending build context to Docker daemon  40.74MB
Step 1/8 : FROM python:3.6
 ---> c1e459c00dc3
Step 2/8 : RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz &&   tar -xvzf ta-lib-0.4.0-src.tar.gz &&   cd ta-lib/ &&   ./configure --prefix=/usr &
&   make &&   make install
 ---> Using cache
 ---> fa92f5557adc
Step 3/8 : ADD app/ /app
 ---> Using cache
 ---> aa958211ea0e
Step 4/8 : WORKDIR /app
 ---> Using cache
 ---> 4de5daf64e69
Step 5/8 : RUN pip install numpy==1.14.0
 ---> Using cache
 ---> 3fe120b17729
Step 6/8 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> ee3c55f27d0a
Step 7/8 : EXPOSE 5000
 ---> Using cache
 ---> f8e47c027304
Step 8/8 : CMD ["/usr/local/bin/python","app.py"]
 ---> Using cache
 ---> 8b23d5300d42
Successfully built 8b23d5300d42
Successfully tagged crypto-signal:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' per
missions. It is recommended to double check and reset permissions for sensitive files and directories.
PS C:\Users\matgb\OneDrive\Crypto\Bot\crypto-signal-master\crypto-signal-master> docker-compose run app
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    from behaviour import Behaviour
  File "/app/behaviour.py", line 8, in <module>
    from analysis import StrategyAnalyzer
  File "/app/analysis.py", line 8, in <module>
    from talib import abstract
ModuleNotFoundError: No module named 'talib'

**Comment by Bird-NZ** [comment]
Got it working. Tried it again outside of Onedrive file structure and it works.

**Comment by shads2** [comment]
Glad you got it working! I would likely not have discovered that.

I would also recommend pulling the changes from today as well as there are some good quality of life changes :)
