### ISSUE TITLE
Figure out what to do about NaN's produced by TA-lib indicators

### ISSUE THREAD

**Issue by jrbartola** [AbenezerMamo/crypto-signal#103]

**Comment by shads2** [comment]
This should be resolved in https://github.com/AbenezerMamo/crypto-signal/pull/109. For any of the TA's where pandas is in use and we have the running tally I am dropping the the rows with NaN. For those not using pandas I am setting the value to None.

This seems like it is probably the best option?

**Comment by shads2** [comment]
Merged!
