### ISSUE TITLE
ModuleNotFoundError: No module named 'behaviours'

### ISSUE THREAD

**Issue by martinjoubert** [AbenezerMamo/crypto-signal#106]
I would like to execute the backtesting server but I get the error "ModuleNotFoundError: No module named 'behaviours'" when I run "python server.py" in "app/behaviours/ui".
I followed "Installation" and "Running the Application" sections without Docker on MacOS 10.13.1 with Python 3.6 installed.

Do you see where the problem is?

**Comment by shads2** [comment]
You would probably need to run `python app/behaviours/ui/server.py` running it from "app/behaviours/ui" would change the application root and prevent it being able to load the rest of the application.

**Comment by jrbartola** [comment]
Apologies. You need to run `python app.py` from the _/app_ directory with the appropriate dependencies installed. Make sure you change the "selected_task" value from "default" to "server" in default_config.json.

**Comment by martinjoubert** [comment]
Thank you! That works after changing the "selected_task" value as you mentioned.
