### ISSUE TITLE
How to add my GDAX account to run backtesting

### ISSUE THREAD

**Issue by martinjoubert** [AbenezerMamo/crypto-signal#107]
Could you please tell me how to include my Coinbase/GDAX account because I think the following part in README.md is deprecated: 

"""Finally, you'll want to create a secrets.json file of the form:

{ "bittrex_key" : "mykey", "bittrex_secret" : "mysecret" }

which you should save in the backend/bot directory. Now you're all set! Integration with more exchanges will be added soon. """

I changed the following section in default-config.json:

"""
  "exchanges": {
    "gdax": {
      "required": {
        "enabled": true
      },
      "optional": {
        "key": "<MY_KEY>",
        "secret": "<MY_SECRET>"
      }
    }
  },
"""

**Comment by jrbartola** [comment]
You don't need an API key to download historical data (from most exchanges, including GDAX). I've just merged some major changes to the UI which now allow you to select an exchange to draw data from. Try pulling the new code and try again after building. I will remove the deprecated README

**Comment by martinjoubert** [comment]
Thanks for the changes!
In addition to what you've written I got a no 'Access-Control-Allow-Origin' issue so it was necessary to add a plugin to Chrome dealing with that.

By the way I think you need to add tenacity in the requirements.
