### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by bitcoinrate** [AbenezerMamo/crypto-signal#11]
it's running fine for me, thank you.

Can an option be added to send the alerts via email please?

**Comment by adbitcoin** [comment]
Bitcoinrate, Can you help put me in the right direction. I have been following updates here and I am trying to start from scratch to make this thing work. So far I have been unsuccessful

**Comment by bitcoinrate** [comment]
I just installed Python Windows version and then the required add ons and it works. I edited the files to include all Bittrex currencies. What is your issue? I'm not expert on this stuff but will help if I can

**Comment by AbenezerMamo** [comment]
Bitcoinrate, there's a lot in the roadmap for this I have to get to before adding email but would be great if you could make a pull request for it. If I add it, I'd probably use something like SendGrid since they have pretty good API's.

adbitcoin, what is the problem you're facing?

**Comment by JPStrydom** [comment]
Hi all. Regarding emails, if you're willing to use your own gmail account (its should work for other email account to) to send emails, you can do the following: 

- Add this to "secrets.json" file:
`"gmail": {
        "address_list": [
            "EXAMPLE_RECIPIENT_1@GMAIL.COM",
            "EXAMPLE_RECIPIENT_2@GMAIL.COM",
            "ETC..."
        ],
        "username": "EXAMPLE_EMAIL@GMAIL.COM",
        "password": "GMAIL_PASSWORD"
    }`
Where "username" would be your email account's username (usually your account's email address), "password" would be your email account's password. and "address_list" is the list of recipients you'd like to send emails to
- Add 'import smtplib' to your imports
- Add the following function to your code: 
'def send_email(subject, message):
    from_address = secrets['gmail']['username']
    to_address_list = secrets['gmail']['address_list']
    login = secrets['gmail']['username']
    password = secrets['gmail']['password']
    smtp_server = 'smtp.gmail.com:587'

    header = 'From: %s\n' % from_address
    header += 'To: %s\n' % ','.join(to_address_list)
    header += 'Subject: %s\n\n' % subject
    message = header + message

    server = smtplib.SMTP(smtp_server)
    server.starttls()
    server.login(login, password)
    errors = server.sendmail(from_address, to_address_list, message)
    server.quit()
    return errors'
You can use this function to send emails with a desired subject and message

I hope this helps. If the author is okay with this strategy, I'll make a PR.

**Comment by AbenezerMamo** [comment]
@JPStrydom Thanks for sharing your solution! Go for it
