### ISSUE TITLE
Server Backtesting - Differing Moving average values

### ISSUE THREAD

**Issue by Bird-NZ** [AbenezerMamo/crypto-signal#114]
In relation to back testing. How would i change the default values for moving averages - currently set at 9 &  15 to be able to test strategies with other values.
Cheers.

**Comment by shads2** [comment]
Right now I don't believe the UI periods are customizable... I think they are all pre-ordained. @jrbartola will have more information... I will label it as a feature request for now.

**Comment by jrbartola** [comment]
That is correct. This is a UI design choice that I couldn't decide on when I was first building the UI, so I just omitted customizable periods for now. I will be adding this at a later date-- In fact, the back-end logic already accommodates variable-length periods for indicators, I just need to think about how to optimize user experience on the front end.

**Comment by Bird-NZ** [comment]
I see, thanks team, looking forward to being about to edit these values in the future.

**Comment by Bird-NZ** [comment]
Sorry, closed by mistake, reopening enhancement now.

**Comment by jrbartola** [comment]
This issue is deprecated. Closing
