### ISSUE TITLE
Notifications setup

### ISSUE THREAD

**Issue by Bird-NZ** [AbenezerMamo/crypto-signal#115]
How do I set up notifications, I've set up gmail details in secrets.json in the format of:
    "gmail": {
      "required": {
        "username": "xxxx@gmail.com",
        "password": "xxxx",
        "destination_emails": ["xxxxx@gmail.com"]
      }
    },

How do I now set up an action / limit that when triggers sends an email?

Cheers,

**Comment by shads2** [comment]
So basically the way it works right now, is that when running a behaviour that has notifier support (which is currently the default or reporting behaviour) it should trigger an alert when the messaging criteria is met.

In the case of the default behaviour it will send a message whenever the hot or cold threshold is crossed for a given analyzer... you can enable/disable alerts on a per analyzer basis in the config file as of a PR merged yesterday.

In the case of the reporter it will just send a notification whenever it is run.

**Comment by Bird-NZ** [comment]
OK thx, I'll have a play with the values and try to trigger a notification.

**Comment by shads2** [comment]
Sure, if something still seems wrong post an update and I'll dig further into the issue :)

**Comment by Bird-NZ** [comment]
Hi, I'm afraid have this not alerting via gmail correctly. 

When I update the secrets.json with my gmail details as above i do not get alerts
But if I update default-config.json with the same details then it alerts BUT it triggers on the first pair it reads and then fails crashing out. see below.

PS C:\docker\cryp> docker-compose run app
Starting default behaviour...
1ST/BTC: RSI: 44.58709603       SMA: 0.00009020 EMA: 0.00008596 Breakout: 0.40000000    Ichimoku: 0.00008721/0.00011199
MACD: -0.00000218
Traceback (most recent call last):
  File "app.py", line 38, in <module>
    main()
  File "app.py", line 33, in main
    behaviour.run(settings['market_pairs'])
  File "/app/behaviours/default.py", line 47, in run
    self.__test_strategies(market_data)
  File "/app/behaviours/default.py", line 137, in __test_strategies
    self.notifier.notify_all(message)
  File "/app/notification.py", line 80, in notify_all
    self.notify_gmail(message)
  File "/app/notification.py", line 114, in notify_gmail
    self.gmail_client.notify(message)
  File "/app/notifiers/gmail_client.py", line 43, in notify
    self.smtp_handler.starttls()
  File "/usr/local/lib/python3.6/smtplib.py", line 749, in starttls
    self.ehlo_or_helo_if_needed()
  File "/usr/local/lib/python3.6/smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/local/lib/python3.6/smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/local/lib/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/local/lib/python3.6/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

Also the email says as an example:
SMA: 1ST/BTC is cold!
EMA: 1ST/BTC is cold!
MACD: 1ST/BTC is cold!

**Comment by shads2** [comment]
I'll look into making the SMTP mailer more reliable

**Comment by shads2** [comment]
Fixed in https://github.com/AbenezerMamo/crypto-signal/pull/139 just waiting for a review.

**Comment by shads2** [comment]
Merged
