### ISSUE TITLE
MACD config and interpretation 

### ISSUE THREAD

**Issue by Bird-NZ** [AbenezerMamo/crypto-signal#117]
Traditionally MACD is calculated by subtracting the 26-day EMA from the 12-day EMA. 
A signal line of a nine-day EMA of the MACD is added top of the derived MACD to denote a buy or sell signal.
This is often denoted as MACD(a,b,c)
Questions: 
1. What EMA values are used in this implemeation of MACD
2. How can we alter / tune these values as a strategy
3. How does this relate to the HOT or COLD values of 1.0? - is this just HOT when it the 9 day signal line crosses above the MACD and COLD when it's below?

**Comment by jrbartola** [comment]
1) We use a python wrapper for [TA-lib](https://github.com/mrjbq7/ta-lib), a trusted open-source library for all of our indicator calculations including MACD. Their implementation is standard-- fast = 12, slow = 26, signal = 9 periods respectively. You can find out more in their documentation.
2) We can adjust the parameters to adjust these values at a later date. 
3) A hot value of 0.0 indicates that when the sign of (MACD - Signal Line) goes from - to +, a threshold alert is triggered. Likewise, a cold value of 0.0 indicates that when the sign of (MACD - Signal Line) goes from + to -, a threshold alert is triggered as well.

**Comment by Bird-NZ** [comment]
Fantastic and comprehensive answer. Two follow ups.
1. Should I lodge a feature request for configurable macd values
2. In your answer to Q3 the fist statement should be "A hot value 1.0 indicates" and not 0.0?

**Comment by shads2** [comment]
jr was correct in saying 0.0, a hot value indicates crossing from a negative number to a positive number and cold is from a positive number to a negative number. Essentially with MACD we are measuring divergence from 0.

**Comment by Bird-NZ** [comment]
Thx people, so to be clear both HOT and COLD is triggered by reaching 0.0 but being HOT or COLD depending on the direction it came from. EG HOT = reaching 0.0 coming from a - value & COLD being reaching 0.0 coming from a + value.

So to alert either way the trigger value should be set to 0.0 for both?

**Comment by jrbartola** [comment]
Correct, if that is the intended behavior you are looking for.

**Comment by Bird-NZ** [comment]
Thx, I'll give it a go and see if I can get the alerting going.

**Comment by cgmckeever** [comment]
wondering if there has been any thought about centerline cross over WRT MACD. Just moving from cold to hot doesnt always mean its in a good territory to buy - meaning, under the centerline there are still considerations to be taken into account[1]

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_average_convergence_divergence_macd

[1] I am in no way a TA expert, so I may be completely off base here in my understanding

**Comment by shads2** [comment]
There is no single TA that should ever solely be considered as the reason to buy. 

Hot in the case of crypto-signal means that particular indicator has crossed into the buy area, but that information alone is not enough to make an informed purchase... nearly every indicator should be combined with complimentary information in order to make an informed decision. I think we currently don't actually do a particularly good job of allowing people to create meaningful alerts for themselves... which is something we'll be considering in the future.

Interestingly enough for MACD there are actually three indicators that can be drawn from the kind of analysis it does. We currently implement only two of them, which are the Zero Line and Signal Line.

**Comment by cgmckeever** [comment]
agreed ... 

hrm ... 

I thought `analyze_macd` looked at the histogram value returned. This must be the zero line analysis ... 

I do now see that `analyze_macd_sl` looks for `macd` to be greater than `macdsignal` (for future note, I think you could just check that `macdhist` is greater than `0` .. but it should all be the same. Not sure which is actually clearer .. 

Thanks!
