### ISSUE TITLE
Web interface doesn't list exchanges

### ISSUE THREAD

**Issue by TheWalterWhite** [AbenezerMamo/crypto-signal#118]
The bot polls info fine in default mode but when in web mode it fails to list any exchanges. It can GET http://localhost:5000/exchanges without error but it doesn't seem to be bringing them back into the web interface. The only option is "Pick and exchange". Running on Ubuntu server 16.04 and Python 3.6.4

**Comment by jrbartola** [comment]
What does the browser console say?

**Comment by TheWalterWhite** [comment]
Here's when the page is loaded: https://i.imgur.com/s9Nqpvq.png
Request headers don't seem to load in chrome or firefox for exchanges...? https://i.imgur.com/Ta8yaeE.png

**Comment by TheWalterWhite** [comment]
Seems like running it on a machine other than local causes it to try and get localhost instead of the server

**Comment by jrbartola** [comment]
@TheWalterWhite Thanks for pointing this out. I have fixed the problem in the most recent commit, 7d3c6b7. Come back and close the issue if it works for you
