### ISSUE TITLE
Hardcoded

### ISSUE THREAD

**Issue by metabaron** [AbenezerMamo/crypto-signal#12]
https://github.com/AbenezerMamo/crypto-signal/blob/e46e8bd620631c8d20a1526d359c5af0a5f45b04/app.py#L22

I was wondering why some of the cryptocurrencies are not mine (from my wallet): you hardcoded the values.

I think you should propose: or to use the default values or to use the one from our wallet.

**Comment by bitcoinrate** [comment]
this is so you can decide which ones you want to track signals on, or add them all. It nothing about what's in your wallet.

**Comment by metabaron** [comment]
ok so could I suggest something:
When the application start, or through a "--help" option, tell that to the user. Understand that most users are non-coders and they will NEVER check the code to understand, as I did, what is happening with the application.
Another way would be to have the pairs in a configuration file

**Comment by AbenezerMamo** [comment]
You can simply add more coins to the array or remove them as you wish. This is documented in the code.

**Comment by metabaron** [comment]
I know I can do it. Not everyone read the code / understand code...
