### ISSUE TITLE
Triple-check profit calculations for backtesting

### ISSUE THREAD

**Issue by jrbartola** [AbenezerMamo/crypto-signal#123]
Sometimes the backtesting profit seems too good to be true. Need to triple-check the logic to ensure correctness.

**Comment by mboncalo** [comment]
How can I help ?

**Comment by jrbartola** [comment]
You could go over the backtesting code to ensure that profits are calculated correctly, perhaps by running the algorithm on a small data set so you can compare the calculated results with results you get by hand

**Comment by jrbartola** [comment]
This issue is deprecated. Closing
