### ISSUE TITLE
Error: 'Connection failure. Temporary failure in name resolution' - ?

### ISSUE THREAD

**Issue by pk13** [AbenezerMamo/crypto-signal#124]
Hi, running simple_bot with bittrex keys and standard strategies I get the following:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 38, in <module>
    main()
  File "app.py", line 33, in main
    behaviour.run(settings['market_pairs'])
  File "/app/behaviours/simple_bot.py", line 49, in run
    market_data = self.exchange_interface.get_symbol_markets(market_pairs)
  File "/app/exchange.py", line 143, in get_symbol_markets
    self.exchanges[exchange].load_markets()
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 867, in load_markets
    markets = self.fetch_markets()
  File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 162, in fetch_markets
    response = self.v2GetMarketsGetMarketSummaries()
  File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 618, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 290, in fetch2
    return self.fetch_requests(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 351, in fetch_requests
    self.raise_error(ExchangeNotAvailable, url, method, e)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 272, in raise_error
    details,
ccxt.base.errors.ExchangeNotAvailable: bittrex GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries HTTPSConnectionPool(host='bittrex.com', port=443): Max retries exceeded with url: /api/v2.0/pub/Markets/GetMarketSummaries (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe6ba0ddeb8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

Any idea why?

**Comment by jrbartola** [comment]
It looks like the applicant cannot connect to the Bittrex server and exhausts all of its retry attempts. Perhaps try checking your network connection and try again?

**Comment by pk13** [comment]
Network connection works well. Checked bittrex keys and different modes but problem persists. Could it be a version problem?

**Comment by shads2** [comment]
Are you running this inside a docker container? It seems like maybe your docker network is perhaps broken. The issue that you are seeing is that the app is unable to resolve the name bittrex.com via DNS, this is not something crypto-signal has any control over as DNS resolution happens at the host level not inside the app itself.

**Comment by pk13** [comment]
Actually it did install curl but "curl: (6) Could not resolve host: bittrex.com", but you're right otherwise. I'll try to set-up docker again

**Comment by shads2** [comment]
Interesting, can you try curling google.com as well? Theoretically if DNS was broken entirely then it should have failed to install curl.

**Comment by jrbartola** [comment]
This doesn't seem to be a problem with crypto-signal as much as it seems a problem with the host's local machine. Closing this issue
