### ISSUE TITLE
localhost error : ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by bigantoine** [AbenezerMamo/crypto-signal#127]
Hello everyone, 

I have tried to install the software and did what was in the README. 
I have changed "default" to "server" in the default-config.json file, however when I run "docker-compose up" in the root directory, it seems that it the default behavior that is running... 

![capture d ecran 2018-01-26 a 17 25 08](https://user-images.githubusercontent.com/25643410/35449808-57d13088-02be-11e8-81fd-eeeedc8c98cc.png)

Also, http://localhost:5000/ doesn't work and the error is "ERR_EMPTY_RESPONSE". 

![capture d ecran 2018-01-26 a 17 31 39](https://user-images.githubusercontent.com/25643410/35449942-ce164b48-02be-11e8-9c88-721e9beda992.png)

Does anyone have any idea why the default behavior seems to run whereas I have changed "default" to "server" in the default-config.json file?

![capture d ecran 2018-01-26 a 17 29 21](https://user-images.githubusercontent.com/25643410/35449863-7fcd335c-02be-11e8-8a7d-d6ef6a864e88.png)

Thank you all very much in advance for your help! :)

**Comment by jrbartola** [comment]
Have you terminated and restarted docker-compose after modifying the JSON file?

**Comment by shads2** [comment]
just to add to what @jrbartola said, you can restart it by running `docker-compose restart`

**Comment by bigantoine** [comment]
Thank you very much guys! Indeed I just had to restart by running docker-compose restart :)
