### ISSUE TITLE
Error: Invalid Argument - Server

### ISSUE THREAD

**Issue by Blackcol** [AbenezerMamo/crypto-signal#128]
Hi every1,

This error happens with different arguments:
![image](https://user-images.githubusercontent.com/32214170/35451706-1a5b51c4-0292-11e8-9077-f928c4d314d8.png)
This is the output:
![image](https://user-images.githubusercontent.com/32214170/35451874-acd35970-0292-11e8-8239-83ab36407d39.png)
Any help?

**Comment by jrbartola** [comment]
Could you elaborate on what you mean by “different arguments”?

**Comment by Blackcol** [comment]
Means that I tryed with different exchange, pair, period, capital, sl, startTime, conditions to buy or sell.. same error for every attempt

**Comment by jrbartola** [comment]
I can't seem to replicate that error. Have you downloaded the latest build and recompiled Docker?

**Comment by Blackcol** [comment]
I'm not using docker, this is the result from the install:
![image](https://user-images.githubusercontent.com/32214170/35455878-a8eaa2b4-02a1-11e8-97ac-17be0dcce6a0.png)
![image](https://user-images.githubusercontent.com/32214170/35455899-c0bc94a6-02a1-11e8-9256-9e2927d053c7.png)

**Comment by jrbartola** [comment]
How are you running the server?

**Comment by Blackcol** [comment]
changed default to server in "default-config.json" and..
![image](https://user-images.githubusercontent.com/32214170/35456954-3b7fdc40-02a5-11e8-9800-6a9896ebc3a6.png)

**Comment by jrbartola** [comment]
I don't see anything immediately wrong with that output. As of just now, the team has decided that it is required to build the project using Docker. Any issues running the project outside of a Docker container will not be serviced. Try building using docker and open another issue if the prolem persists. Apologies for the inconvenience.
