### ISSUE TITLE
RSI is off on 5M and 30M

### ISSUE THREAD

**Issue by hanyoon93** [AbenezerMamo/crypto-signal#13]
RSI is off on every pair, on both the 5m and 30m calculations (haven't checked the other timeframes). 

I am comparing the data with TradingView and Cryptowat.ch.

**Comment by AbenezerMamo** [comment]
The value should be off by only 1 to 3 points. This is due to the fact that the RSI isn't smoothed out - thought the calculations should be correct either way.

I'll address this soon. There are just a lot on my plate IRL.

**Comment by pcartwright81** [comment]
I think the average is wrong.  Try this
Change 
average_gain = (sum(advances) / len(advances))
average_loss = (sum(declines) / len(declines))

To
average_gain = (sum(advances) / period
average_loss = (sum(declines) / period

According to the non smoothed rsi formula that is the calculation.  Still haven't figured out the formula for the smoothed calculation.  During testing I noticed ~20 error.  Now it is ~3 off.

**Comment by AbenezerMamo** [comment]
Thanks for the correction! I'll implement the fix but feel free to make a pull request. Helps everyone out :)

**Comment by hanyoon93** [comment]
@pcartwright81 Just tried your fix -- the RSI is still off by 10-25. I'm using tradingview to reference the 'correct' values. Any thoughts?

**Comment by pcartwright81** [comment]
Just noticed that too.  On my tester it was much closer for the market I was testing.  Honestly I have been working on this formula for a while.  One thing I also noticed is between Bitterex and Trading view the numbers don't match, but they are only 1% off.

**Comment by pcartwright81** [comment]
Sorry screwed up my code base by commenting out a lot of stuff that should not be merged into your code.  I can't create a pull request.  Below is the method that I changed and is uses true smoothing.  My disclaimer is I am not a python programmer I am actually a c# programmer.   The code looks at 3 times the period.

Below is the code:

def calculateRSI(coin_pair, period, unit):
    """
    Calculates the Relative Strength Index for a coin_pair
    If the returned value is above 70, it's overbought (SELL IT!)
    If the returned value is below 30, it's oversold (BUY IT!)
    """
    closing_prices = getClosingPrices(coin_pair, period * 3, unit)
    count = 0
    change = []
    # Calculating price changes
    for i in closing_prices:
        if count != 0:
            change.append(i - closing_prices[count - 1])
        count += 1
        if count == 15:
           break
    # Calculating gains and losses
    advances = []
    declines = []
    for i in change:
        if i > 0:
            advances.append(i)
        if i < 0:
            declines.append(abs(i))
    average_gain = (sum(advances) / 14)
    average_loss = (sum(declines) / 14)
    newAvgGain = average_gain
    newAvgLoss = average_loss	
    for i in closing_prices:
        if count > 14 and count < len(closing_prices):
          close = closing_prices[count]
          newChange = close - closing_prices[count - 1]
          addLoss = 0;
          addGain = 0;
          if newChange > 0:
              addGain = newChange
          if newChange < 0:
              addLoss = abs(newChange)
          newAvgGain = (newAvgGain * 13 + addGain) / 14
          newAvgLoss = (newAvgLoss * 13 + addLoss) / 14  
          count += 1
                
    rs = newAvgGain / newAvgLoss;
    newRS = 100 - 100 / (1 + rs);          
    return newRS

**Comment by hanyoon93** [comment]
@pcartwright81 Very accurate! Thank you bud :)
