### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by kadnan** [AbenezerMamo/crypto-signal#14]
Want to know about MACD implementation

**Comment by AbenezerMamo** [comment]
It's on pause for a bit as I transition into my next role (IRL too OP). I have quite a lot of improvements that I'll be porting from my personal tool to this public repo. More on that soon (Valve time)

**Comment by kadnan** [comment]
hmm.. you might like to move onto PANDAS due to better performance and built-in features like SMA, EMAs etc
