### ISSUE TITLE
Error starting Server (Backtesting)

### ISSUE THREAD

**Issue by Bird-NZ** [AbenezerMamo/crypto-signal#146]
I have had this running in the past but now backtesting not starting. (works fine in "default")

default-config.json set to  - "selected_task": "server"
PS C:\docker\cryp2> docker-compose run app
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

But once I've run:
"npm install" & then "npm run build" - Which both complete 
I then go to run:
"docker-compose up"
and I get:
PS C:\docker\cryp2> docker-compose up

Starting cryp2_app_1 ... error

ERROR: for cryp2_app_1  Cannot start service app: driver failed programming external connectivity on endpoint cryp2_app_
1 (6ca1750249e9c24f91f391bcde21b96c70c1e9a263488a89906eae0d57430c39): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5000:tcp:172.20.0.3:5000: input/output error

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint cryp2_app_1 (6ca1750249e9c24f91f391bcde21b96c70c1e9a263488a89906eae0d57430c39): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5000:tcp:172.20.0.3:5000: input/output error
ERROR: Encountered errors while bringing up the project.

**Comment by jrbartola** [comment]
This sounds like a Docker-specific issue rather than an issue with crypto-signal. @shads2 Any thoughts?

**Comment by Bird-NZ** [comment]
Sorry, was meaning to update on this. Will close this issue as yes it's a Docker specific issue.. 
Solution: It is a port conflict issue that restarting docker (and hence releasing used ports) fixed.
