### ISSUE TITLE
Simple bot error on binance

### ISSUE THREAD

**Issue by TheWalterWhite** [AbenezerMamo/crypto-signal#147]
Simple bot works more or less on bittrex but when switching over to binance it throws the error 
'''
ccxt.base.errors.ExchangeError: binance fetchOpenOrders requires a symbol param
'''
All other settings are set the the defaults and it throws this regardless of the market pairing

**Comment by shads2** [comment]
Simple bot should not be used at this time, it's got a wide variety of issues. This will get fixed in due course, but I would highly recommend not using it as a source of information for anything right now. It will only make you sad :'(
