### ISSUE TITLE
RSI value not correct ?

### ISSUE THREAD

**Issue by mboncalo** [AbenezerMamo/crypto-signal#155]
Hi,
I was running the bot to check if the values are the same with the ones that I see on the exchange:
ETH/BTC:        Breakout: 0.0   RSI: 81.59      
ZCL/BTC:        Breakout: 0.0   RSI: 52.49      
XVG/BTC:        Breakout: 0.0   RSI: 40.08      
EMC2/BTC:       Breakout: 0.0   RSI: 40.69      
EMC/BTC:        Breakout: 0.4   RSI: 56.50      
Sleeping for 3 seconds
ETH/BTC:        Breakout: 0.0   RSI: 81.59      
ZCL/BTC:        Breakout: 0.0   RSI: 52.49      
ADA/BTC:        Breakout: 0.0   RSI: 43.61      
XVG/BTC:        Breakout: 0.0   RSI: 40.08      
EMC2/BTC:       Breakout: 0.0   RSI: 40.69      
EMC/BTC:        Breakout: 0.4   RSI: 56.50      
Sleeping for 3 seconds
ETH/BTC:        Breakout: 0.0   RSI: 81.59      
ZCL/BTC:        Breakout: 0.0   RSI: 52.49      
ADA/BTC:        Breakout: 0.0   RSI: 43.61      
XVG/BTC:        Breakout: 0.0   RSI: 40.08      
EMC2/BTC:       Breakout: 0.0   RSI: 40.68      
EMC/BTC:        Breakout: 0.4   RSI: 56.50      
Sleeping for 3 seconds
ETH/BTC:        Breakout: 0.0   RSI: 81.55      
ZCL/BTC:        Breakout: 0.0   RSI: 52.49      
ADA/BTC:        Breakout: 0.0   RSI: 43.61      
XVG/BTC:        Breakout: 0.0   RSI: 40.04      
EMC2/BTC:       Breakout: 0.0   RSI: 40.68      
EMC/BTC:        Breakout: 0.4   RSI: 56.50      
Sleeping for 3 seconds
ETH/BTC:        Breakout: 0.0   RSI: 81.55      
ZCL/BTC:        Breakout: 0.0   RSI: 52.49      
ADA/BTC:        Breakout: 0.0   RSI: 43.61      
XVG/BTC:      Breakout: 0.0   RSI: 40.04      

It's very unlikely for a coin with high transaction volume to have the same value after 9,18,27 seconds.

**Comment by shads2** [comment]
By default it uses hourly candles., the smallest value candles any exchange will give you is 1 minute candles... so even after 27 seconds you still aren't likely to see a change.

**Comment by cgmckeever** [comment]
agree that over the minute RSI will not be affected .. 
Not sure if some of the broader discrepancy  is based on the memory of RSI not being part of TA-LIB

https://www.quantopian.com/posts/ta-lib-rsi-using-something-other-than-close-price
http://ta-lib.org/d_api/ta_setunstableperiod.html

been doing some research around this

**Comment by cgmckeever** [comment]
update FWIW .. appears that using 14 periods with 120 periods of history aligns TA-Lib nicely with TradingView at the 1 minute interval .. YMMV

**Comment by shads2** [comment]
Also worth noting that the python binding library documentation will tell you what functions do not have the unstable flag set and thus are susceptible to variance due to time period: http://mrjbq7.github.io/ta-lib/func_groups/overlap_studies.html

**Comment by shads2** [comment]
There is no further work to do on this ticket I am closing it for now.
