### ISSUE TITLE
1 Week and 1 Month Timescales Unavailable

### ISSUE THREAD

**Issue by hanyoon93** [AbenezerMamo/crypto-signal#16]
Seems like Bittrex API no longer supports 1 week and 1 month historical prices. 

Error:

  return historicalData['result'][-period:]
  TypeError: 'NoneType' object is not subscriptable

**Comment by AbenezerMamo** [comment]
@hanyoon93 Can you share more info on this?

**Comment by Andreilys** [comment]
Are you passing in the right format to BITTREX_CLIENT.get_historical_data(coin_pair, period, unit)?

If your coin_pair isn't in the "BTC-XXX" format then you will get a None value

**Comment by shads2** [comment]
I think I am going to close this, ccxt now provides the interface for history and we support whatever they support.
