### ISSUE TITLE
Split StrategyAnalyzer and move the indicators to separated classes

### ISSUE THREAD

**Issue by riterrani** [AbenezerMamo/crypto-signal#166]
Hi first of all I want to say thanks to the developers, this is a great project and I think that has great future.

I think that would be nice to split a bit StrategyAnalyzer, it has too much logic. If the idea is to add more indicator should be easier to add one, and making it modular is going to prevent conflicts I think.

I thought in something like this https://github.com/riterrani/crypto-signal/commit/1c0b116999c49ef47d65ad4055d9cc0d2d26deb2 . This is my first time working on Python so I am sure that the code is not ready for merge, but that's the basic idea.

I am sorry for my english, is not my first  language.

**Comment by shads2** [comment]
I've actually been thinking about doing something along those lines for quite some time, just hasn't reached the top of my list yet. It's grown sufficiently that it's probably worth doing sometime soon.

**Comment by jrbartola** [comment]
@riterrani Could you submit a pull request for this commit so we can get it merged in?

**Comment by shads2** [comment]
Implemented in https://github.com/AbenezerMamo/crypto-signal/pull/179

**Comment by shads2** [comment]
merged
