### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by denigada** [AbenezerMamo/crypto-signal#18]
hello I get this error in terminal then I try to run:

`Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from bittrex import Bittrex
  File "/Users/deniz/Downloads/crypto-signal-master/bittrex.py", line 18, in <module>
    import requests
ImportError: No module named requests`

**Comment by Stoner19** [comment]
You probably didn't install the necessary requirements in order to run the script. You need to do `pip install -r requirements.txt` first.
