### ISSUE TITLE
Not able to execute the script

### ISSUE THREAD

**Issue by ernestjeba** [AbenezerMamo/crypto-signal#2]
Hi, Thanks for creating such a technical analysis. 
I am unable to execute the script. README doesn't have the steps to execute the script.

`bin/python ../app.py `
Traceback (most recent call last):
  File "../app.py", line 5, in <module>
    from twilio.rest import Client
ImportError: No module named twilio.rest

`bin/pip install twilio`
-bash: bin/pip: /Users/Mamo/Desktop/crypto-signal/env/bin/python: bad interpreter: No such file or directory

`grep -r Mamo .`
./bin/activate:VIRTUAL_ENV="/Users/Mamo/Desktop/crypto-signal/env"
./bin/activate.csh:setenv VIRTUAL_ENV "/Users/Mamo/Desktop/crypto-signal/env"
./bin/activate.fish:set -gx VIRTUAL_ENV "/Users/Mamo/Desktop/crypto-signal/env"
./bin/chardetect:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
./bin/easy_install:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
./bin/easy_install-2.7:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
./bin/pip:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
./bin/pip2:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
./bin/pip2.7:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
./bin/python-config:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
./bin/wheel:#!/Users/Mamo/Desktop/crypto-signal/env/bin/python
Binary file ./lib/python2.7/distutils/__init__.pyc matches
Binary file ./lib/python2.7/fnmatch.pyc matches
./lib/python2.7/site-packages/pip-9.0.1.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/bin/pip,sha256=r13MeYbKxv_jJRBJpEUD1wPa6i5XEM3i2BIkvWFAfbA,237
./lib/python2.7/site-packages/pip-9.0.1.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/bin/pip2,sha256=r13MeYbKxv_jJRBJpEUD1wPa6i5XEM3i2BIkvWFAfbA,237
./lib/python2.7/site-packages/pip-9.0.1.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/bin/pip2.7,sha256=r13MeYbKxv_jJRBJpEUD1wPa6i5XEM3i2BIkvWFAfbA,237
./lib/python2.7/site-packages/pip-9.0.1.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/lib/python2.7/site-packages/pip-9.0.1.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
./lib/python2.7/site-packages/setuptools-36.5.0.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/bin/easy_install,sha256=lN7Gzsg-FasNmVvS9uvHjUzwCgKxJ9Q4UEd3a4tU3Hs,265
./lib/python2.7/site-packages/setuptools-36.5.0.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/bin/easy_install-2.7,sha256=lN7Gzsg-FasNmVvS9uvHjUzwCgKxJ9Q4UEd3a4tU3Hs,265
./lib/python2.7/site-packages/setuptools-36.5.0.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/lib/python2.7/site-packages/setuptools-36.5.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
./lib/python2.7/site-packages/wheel-0.30.0.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/bin/wheel,sha256=F7UXKQdMLDVmEBgOF_E_eaGoD2TBlc__eALGxnt0lK0,244
./lib/python2.7/site-packages/wheel-0.30.0.dist-info/RECORD:/Users/Mamo/Desktop/crypto-signal/env/lib/python2.7/site-packages/wheel-0.30.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4

**Comment by AbenezerMamo** [comment]
The latest changes should be able to fix this issue. The env was removed in place of a requirements file that should download what you need. Also, this was developed on Python 3.4
