### ISSUE TITLE
Getting the RSI curve

### ISSUE THREAD

**Issue by denigada** [AbenezerMamo/crypto-signal#22]
Hello, I would like to ask you all if you have any ideas on how we can use the calculateRSI function to calculate the RSI of a few minutes ago. For example, I want to get the 30 min RSI of 5mins earlier and get the RSI of now, to find out if it is curving up or down.

**Comment by AbenezerMamo** [comment]
I see...I think you'd need to add some kind of local database that would store the RSI values every time you make a request. Then you can query that database for historical RSI values
