### ISSUE TITLE
EMA and SMA gives the same result every time

### ISSUE THREAD

**Issue by denigada** [AbenezerMamo/crypto-signal#23]

**Comment by AbenezerMamo** [comment]
The EMA is the Exponential Moving Average and the SMA is the Simple Moving Average. The EMA favors the most recent price data as opposed to taking an average of an entire period. That being said, it's highly unlikely that these two numbers should be the same. Can you share a printout?

**Comment by matthewlilley** [comment]
Strange, I have the opposite.

Using TA-Lib, I get the same results for SMA, and EMA when using the same period count, and historical data. But the SMA and EMA functions of this repository, return slightly different values when using the same period count, and historical data.

        `sma = SMA(input, timeperiod=period_count)[-1]
        ema = EMA(input, timeperiod=period_count)[-1]
        sma_value = ma_analyzer.get_sma_value(period_count, historical_data)
        ema_value = ma_analyzer.get_ema_value(period_count, historical_data)
        self.logger.info('TA-Lib   | SMA: %s | EMA: %s | RSI:' % (format(sma, '.7f'), format(ema, '.7f')))
        self.logger.info('Original | SMA: %s | EMA: %s' % (format(sma_value, '.7f'), format(ema_value, '.7f')))'

Shouldn't this use of SMA and EMA, together with the same data and period, be the same as TA-Lib?
