### ISSUE TITLE
calculateSMA errors

### ISSUE THREAD

**Issue by zstergios** [AbenezerMamo/crypto-signal#24]
Hi,
first of all thank you for giving this code to public.

I have converted your code to PHP because I'm expirienced on PHP coding.

I found some issues on calculateEMA function
a) constant = (2 / (period + 1)) not used in the function, have you missed to included it on summaring variables?

b) closing_prices[-1] is underfined, do you mean closing_prices[1]?

Also I have a question about getHistoricalData function, you return historicalData['result'][-period:]

I don't actually understand in PY what you mean (minus-) period and : . I have found that is substracting a part of array, can you explain the minus?
I have "transcoded" to PHP to return return array_slice(historicalData['result'],$period);

Raw Result of historicalData['result']

```
Array
(
    [0] => Array
        (
            [O] => 0.051085
            [H] => 0.05120246
            [L] => 0.051005
            [C] => 0.05120246
            [V] => 478.1481531
            [T] => 2017-10-27T21:30:00
            [BV] => 24.42278885
        )

    [1] => Array
        (
            [O] => 0.05120201
            [H] => 0.05144221
            [L] => 0.051202
            [C] => 0.05143804
            [V] => 649.60716864
            [T] => 2017-10-27T22:00:00
            [BV] => 33.28065136
        )

    [2] => Array
        (
            [O] => 0.05139
            [H] => 0.05151505
            [L] => 0.05128999
            [C] => 0.051295
            [V] => 404.79272826
            [T] => 2017-10-27T22:30:00
            [BV] => 20.8108504
        )
)

```

**Comment by bitcoinrate** [comment]
great work. Would you mind sharing your PHP code? I am better at tweaking that than anything else. Thanks in advance

**Comment by zstergios** [comment]
I have not finished the debuging. It's easy to convert it if you have some knowlegde on PHP.
Also I have not run the origianl software to compare the results becaue I don;t have Py ob my PC.

Just for the history, probably minus perido :, means return all last 9 elements, so in PHP this 

`return array_slice($rsp['result'],-$period);`

**Comment by zstergios** [comment]
Something goins wrong with code....
http://prntscr.com/hk8j1y

None pair is breaking out....

**Comment by AbenezerMamo** [comment]
@zstergios Yea, the "-" when specifying an array index just means it counts backgrounds. [-1] would make it the last and [-2] would make it second to last.

In regards to the break outs, it could just be that none of the coins you added have met the requirements to trigger the breakout. You can change the variables to suit your own needs
