### ISSUE TITLE
Script stops at BTC-XMR

### ISSUE THREAD

**Issue by albabosh** [AbenezerMamo/crypto-signal#27]
Script stops at:

BTC-XMR:        Breakout: #Bagholding   RSI: 46.1423413592

Is it normal ?

**Comment by GiorgosK** [comment]
Same here

**Comment by AbenezerMamo** [comment]
@albabosh  Can you give some more info? This is a bit ambiguous

**Comment by unickq** [comment]
@AbenezerMamo 
Same here:
Win10, Python 3.6.4
\crypto-signal\app\secrets.json

```json
{
    "bittrex_key" : "MY_REAL_KEY",
    "bittrex_secret" : "MY_REAL_SECRET",
    "twilio_key": "TWILIO_API_KEY",
    "twilio_secret": "TWILIO_SECRET",
    "twilio_number": "TWILIO_PHONE_NUMBER",
    "my_number": "YOUR_PHONE_NUMBER"
}
```

Executed by ```python crypto-signal\app\app.py``` and seems like app has frozen.

1. 
![screenshot_1](https://user-images.githubusercontent.com/6696821/34377067-f58fdc4a-eaf7-11e7-965d-3cecb12497f9.png)

**Comment by GiorgosK** [comment]
@all as i said earlier i dont think its stuck just runs one stops it 
it runs every 300 seconds to check all pairs

**Comment by albabosh** [comment]
These are not all pairs available at bittrex.

**Comment by Satoshinaire** [comment]
As far as I can tell, this is expected, as by default the app effectively is a demo. It runs on a set list of trading pairs showing their RSI every 5 minutes.

**Comment by DuckyOfAwesome** [comment]
Open App.py, it does these trading pairs and waits for 300 seconds and then does them again.  It is very clear that this is working as intended.
