### ISSUE TITLE
Coercing Unicode

### ISSUE THREAD

**Issue by DuckyOfAwesome** [AbenezerMamo/crypto-signal#35]
`  File "app.py", line 21, in <module>
    with open(SECRETS_FILE_PATH) as secrets_file:
TypeError: coercing to Unicode: need string or buffer, PosixPath found`

Fixed by changing to:
`    with open(str(SECRETS_FILE_PATH)) as secrets_file:
`

**Comment by Andreilys** [comment]
Great thanks! Will add that to the next merge
