### ISSUE TITLE
RSI gives different result with Bittrex

### ISSUE THREAD

**Issue by JustinNguyenME** [AbenezerMamo/crypto-signal#41]
I try to put period from Bittrex to 18 to match strategy from the source code but it still gives the different result.

So I make another test is to increase the period to 100 from source code and Bittrex, what I expect is RSI should around 45~55 but it doesn't.

**Comment by Lokraan** [comment]
To match bittrex, period count has to be a high number like 10000 in order to get all possible history for the market. This is because bittrex uses all available data to calculate RSI.

**Comment by shads2** [comment]
Like @Lokraan said, currently the number of samples is low enough that it doesn't match the data from bittrex. There is a PR that is waiting for review, that has a bandaid that should fix this.

**Comment by shads2** [comment]
This has been merged and should be resolved.
