### ISSUE TITLE
ImportError: No module named rest

### ISSUE THREAD

**Issue by k3nb3l** [AbenezerMamo/crypto-signal#42]
Hi guys,

I tried to run it on a raspberry pi. 

following error message

Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from notification import Notifier
  File "/crypto-signal-master/app/notification.py", line 6, in <module>
    from notifiers.twilio import TwilioNotifier
  File "/crypto-signal-master/app/notifiers/twilio.py", line 7, in <module>
ImportError: No module named rest

I just installed all requirements, it looks like a problem with twilio, 
http://twilio-python.readthedocs.io/en/latest/faq.html

Any idea or thoughts?

Many thanks in advance.

**Comment by shads2** [comment]
Interesting, I have no idea why I don't see that issue in the docker environment but I'll submit a fix.

**Comment by shads2** [comment]
Are you able to test for me with this branch: https://github.com/AbenezerMamo/crypto-signal/tree/fix_for_i42 ?

**Comment by k3nb3l** [comment]
TX, I´ll check.

**Comment by k3nb3l** [comment]
I am using bittrex and get an error like this:

docker run -it --rm --env-file .env crypto-signal
Traceback (most recent call last):
  File "app.py", line 83, in <module>
    main()
  File "app.py", line 61, in main
    get_signal(coin_pairs, strategy_analyzer, notifier)
  File "app.py", line 65, in get_signal
    rsi_value = strategy_analyzer.analyze_rsi(coin_pair)
  File "/app/analysis.py", line 35, in analyze_rsi
    time_unit=time_unit
  File "/app/exchange.py", line 33, in get_historical_data
    limit=period_count))
  File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 384, in fetch_ohlcv
    market = self.market(symbol)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1011, in market
    raise ExchangeError(self.id + ' does not have market symbol ' + str(symbol))
ccxt.base.errors.ExchangeError: bittrex does not have market symbol BTC-ETH
Makefile:9: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by k3nb3l** [comment]
I got it running locally

pi@raspi:/download/crypto-signal-fix_for_i42/app $ sudo python app.py 
XVG/BTC: 	Breakout: 0 	RSI: 86.28 	SMA: 0.0000006 	EMA: 0.0000006 	IMA: 0.0000002 	IMB: 0.0000003

But I've no clue where the pair is coming from. If I add a secrets.json file with pairs I get
some errors. 
Could you send me a example please?

**Comment by shads2** [comment]
Currently in master if you run it without any pairs specified and you provide bittrex keys it will look up the market pairs in your account and use them instead. This behaviour changes in https://github.com/AbenezerMamo/crypto-signal/pull/43 where it will do all pairs on the requested exchange.

When specifying the pairs they need to be added in the format of Base/Quote... for example: XVG/BTC
