### ISSUE TITLE
Rename twilio.py

### ISSUE THREAD

**Issue by dvalent** [AbenezerMamo/crypto-signal#52]
Hi! thanks for work! 
I get a 
“ImportError: No module named twilio.rest”
and renamed the twilio.py file
https://stackoverflow.com/questions/35180322/importerror-no-module-named-twilio-rest
also to use on python 2.7 
changed urllib.request to urllib2 in integram.py

**Comment by shads2** [comment]
I have a fix for this but was waiting for feedback on https://github.com/AbenezerMamo/crypto-signal/issues/42. That branch is unfortunately now too far behind master... I'll resubmit the fix later today
