### ISSUE TITLE
Build Failed on Windows

### ISSUE THREAD

**Issue by theboywonder** [AbenezerMamo/crypto-signal#60]
Any idea why I might be getting this?

```
PS C:\Users\Username\Documents\cryptosignals\crypto-signal> docker build -t cs .
Sending build context to Docker daemon  3.836MB
Step 1/5 : FROM python:3.6
 ---> c1e459c00dc3
Step 2/5 : ADD app/ /app
 ---> Using cache
 ---> dd3131901afb
Step 3/5 : WORKDIR /app
 ---> Using cache
 ---> d401ea36bbfb
Step 4/5 : RUN pip install -r requirements.txt
 ---> Running in 238d1cd4f7af
Collecting asn1crypto==0.22.0 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/asn1crypto/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/asn1crypto/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/asn1crypto/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/asn1crypto/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/asn1crypto/
  Could not find a version that satisfies the requirement asn1crypto==0.22.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for asn1crypto==0.22.0 (from -r requirements.txt (line 1))
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```
 
Docker is Version 17.12.0-ce-rc4-win44 (14896), running on Windows 10. This is the first time I've ever tried to 'build' an image, but I've pulled and run other images successfully before.

**Comment by theboywonder** [comment]
I think this was a temporary issue with reaching pypi.python.org. It seems to have built now.

**Comment by theboywonder** [comment]
Now hitting:

```
PS C:\Users\Username\Documents\cryptosignals\crypto-signal\app> python app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    import logs
  File "C:\Users\Username\Documents\cryptosignals\crypto-signal\app\logs.py", line 8, in <module>
    import structlog
ModuleNotFoundError: No module named 'structlog'
```

**Comment by shads2** [comment]
Your first issue definitely looks like just a temporary timeout issue. In your second post it appears you are trying to run it on your host instead of running the docker container? 

If you want to run it on your host you will need to do the pip install on your host instead of building the container.

**Comment by shads2** [comment]
Closing this due to no further updates.

**Comment by theboywonder** [comment]
Apologies for the lack of reply. With regard to "In your second post it appears you are trying to run it on your host instead of running the docker container?" - I had no idea this was the case.

I have docker installed and ideally would like to run a docker container, but the documentation states:

> Next, to create the docker image run `make build` in the root of the project directory.

`Make build` isn't recognised on Windows. Nor is `docker make`. Google doesn't shed any light on the issue either. I can't even recall how I arrived at trying `docker build -t cs .` to be honest.

**Comment by theboywonder** [comment]
On a different Windows 10 machine (running Docker 17.12.0-ce-win47 (15139) from the stable channel).

I've tried all configurations of `docker build` and just keep getting:

`unable to prepare context: unable to evaluate symlinks in context path: readlink C:\Users\Username\Documents\crypto-signal: The process cannot access the file because it is being used by another process.`

I've tried doing this from multiple different locations on the disk (previously it was in OneDrive so I suspected file locking issues).

**Comment by theboywonder** [comment]
I moved the directory to the root of the C:\ and it builds. I guess OneDrive and Documents are using symlinks. 

It's also not possible to create a file called '.env' on Windows from the GUI so I had to do this from the command line.

```
PS C:\crypto-signal> docker-compose.exe run app
Creating network "cryptosignal_default" with the default driver
Pulling app (crypto-signal:latest)...
ERROR: pull access denied for crypto-signal, repository does not exist or may require 'docker login'
```

I tried `docker login` and providing my details, which worked, but running docker-compose.exe run app failed again.

**Comment by shads2** [comment]
Running make on windows requires the GNU build tools http://www.mingw.org/wiki/msys

If you want to run the docker build manually the magic invocation is: `docker build -t crypto-signal .` this is found in the Makefile. The reason your attempts so far haven't worked it is because the container you build needs to be called crypto-signal

To create the .env file you will need to use either an IDE to create it or use the command line and run either `touch .env` or `cp some_file .env`. Microsoft explorer is opinionated in some weird ways on file names... but it is not an OS limitation. 

The early stages of this project were largely built on windows, right now there is however a lack of documentation... but that is due to the fact this project is a far cry from ready for general consumption.

**Comment by theboywonder** [comment]
Thanks again for the reply (didn't have issues with the env file, but I was just pointing it out for future doc updates).

Once I removed the crysig image, and rebuilt using crypto-signal it seemed fine. I wasn't aware that I couldn't use custom names of images. Thanks.

Can I ask what the difference is between the two following options:
```docker pull <imagename>
docker create -name something
docker container start something```

and
```
docker build -t crypto-signal .
docker-compose.exe run app
```

My understanding of the first is that I pull down an image from Docker hub, create a container, and start the container.
My understanding of the second is that I `build` and image from source files... but why then do I have to use docker-compose.exe to `run app`? Is all the configuration not contained in some build image somewhere on my computer? It confuses me why I'd build an image and then `run app` which obviously is referencing the app directory from this cloned repo.

Sorry for so many questions. You'd never believe I was a Windows admin of over 11 years, and run a large VMware/Cisco UCS platform and been automating them with PowerShell for over 7 years. Linux and Docker are still a relative mystery to me.

**Comment by shads2** [comment]
Sure, happy to demystify some docker! That is a large part of my day job anyway, but there is a lot to unpack in your question so this explanation might be quite long and I apologise if I sound patronising or I am explaining things you already know.

Lets start with `docker pull <imagename>` you're understanding of this is correct, we have not published this container to docker hub _yet_ however so you can't pull it. It's also worth noting that the image name may contain the name of a docker registry which allows it to be pulled from places other than docker hub.

Next `docker build -t <imagename> .` tells docker to essentially "compile" the application and create <imagename>. A common problem that new docker users often have is wrapping their head around the fact an _image_ is different to a _container_. An analogy I like to use for sysadmins is that an image is an ISO while a container is the OS you install from an ISO.

The commands
```
docker create --name <something> <imagename>
docker start <something>
```
are functionally equivalent to running the command
```
docker run --name <something> <imagename>
```
Using docker run actually performs both of the steps involved in docker create and docker start. You don't see people using create and start very often. What this does though is tell docker that for <imagename> I want to start an instance of this application (also called a container) with the name <something>

Last of all `docker-compose run app` does not do what you think it does. Docker-compose is a tool that is often used for a few different jobs. Common ones are:
1. It allows you to orchestrate multiple containers together (you can see this in docker-compose.reporter.yml in the repo)
2. To provide a way of running a container that has common settings pre-configured
3. As a portable dev environment, that mounts the code base into a container running the image for that application (you can see this in docker-compose.yml)

So what the docker-compose command actually says in the case of this repo is: In docker-compose.yml find the instructions for the container labelled "app" and then run it with the settings configured.

I hope this helps your understanding.

**Comment by theboywonder** [comment]
@shads2 Thank you so much for the thorough explanation. That's really clear and has helped a lot. Can't thank you enough. I'll be pasting this comment into a OneNote document I created to store notes on Docker so I don't forget it!
