### ISSUE TITLE
Missing documentation for trading pairs

### ISSUE THREAD

**Issue by mfreeman451** [AbenezerMamo/crypto-signal#62]
The link that is supposed to describe how to setup trading pairs in the settings is broken, need to know what the proper format of trading pairs is.

**Comment by shads2** [comment]
Things are still very much in development right now and as a result the documentation is lagging. The proper format is base_currency/quote_currency so BTC/BURST for example.

**Comment by Andreilys** [comment]
Thanks @mfreeman451, seems that link got taken down so I've updated the README
