### ISSUE TITLE
entering pairs in to the default-config.json

### ISSUE THREAD

**Issue by tomma100** [AbenezerMamo/crypto-signal#64]
i am trying to enter the pair list in to the json file like this 

  "settings": {
    "app_mode": "user",
    "symbol_pairs": "USDT/ETH",
    "loglevel": "",
    "update_interval": 300,
    "selected_task": "default"
  },

but when i run with docker i get 

Traceback (most recent call last):
  File "app.py", line 43, in <module>
    main()
  File "app.py", line 40, in main
    notifier)
  File "/app/behaviours/default.py", line 9, in run
    market_data = exchange_interface.get_symbol_markets(symbol_pairs)
  File "/app/exchange.py", line 70, in get_symbol_markets
    symbol_markets[exchange.id][symbol_pair] = exchange.markets[symbol_pair]
KeyError: 'U'

wonder if anyone can see the obvious mistake i am probably making!!!  

thanks

**Comment by noconstruct** [comment]
https://jsonlint.com/ try validating the entire file, but its mostly because it should look something like 

`"symbol_pairs": ["BCH/BTC", "XMR/BTC", "ETH/BTC", "ETH/USDT", "BTC/USDT"], `

**Comment by tomma100** [comment]
superb - that fixed it!  thank you 

might be an idea to put that in the readme

**Comment by shads2** [comment]
Right now the code base is generally not stable and the contents of the readme tend to get invalidated every couple of days. We do our best to keep it up to date but things are changing quite rapidly as it is still early days.

Still glad you found a solution to your issue :)
