### ISSUE TITLE
Binance

### ISSUE THREAD

**Issue by skupfer** [AbenezerMamo/crypto-signal#68]
Does it work with binance? Made a short test and changed bittrex in "exchanges" but I still receive USDT/BTC and such which isn't available on binance. I guess it would have to be implemented first?

**Comment by shads2** [comment]
Theoretically it should support binance though right now 99% of the testing is done with bittrex. If you don't define what market pairs to use we just use whatever market pairs the API of the exchange tells us is available.

I will however do some further testing and update this thread.

**Comment by shads2** [comment]
As far as I can tell this is working as intended.
https://api.binance.com:443 "GET /api/v1/klines?symbol=BTCUSDT&interval=1d&limit=100 HTTP/1.1" 200 None
https://api.binance.com:443 "GET /api/v1/klines?symbol=BTCUSDT&interval=5m&limit=100 HTTP/1.1" 200 None
BTC/USDT:       Breakout: 0.0   RSI: 83.91      SMA: 5056.7666667       EMA: 5113.6783333       IMC: 5004.2900000/6210.2950000  MACD: -1.4230856

It's entirely possible it just is not listed on their UI yet
