### ISSUE TITLE
Defined market pairs do not seem to work

### ISSUE THREAD

**Issue by ejzwiers** [AbenezerMamo/crypto-signal#70]
The updated market_pairs i'd like to monitor within app/default-config.json, does not seem to work.
The line I put in:
"market_pairs": ["BTC/ETH" , "1ST/BTC"]

still all pairs are scanned

please advise

**Comment by shads2** [comment]
Are you trying to use the rsi_bot behaviour? Because that does not currently function.

The default behaviour is the only one that functions correctly at this point in time.

**Comment by ejzwiers** [comment]
Within app/default-config.json I only changed the  "market_pairs": ["ETH/BTC","ADA/BTC"],
This is my config file:
{
  "settings": {
    "log_mode": "text",
    "market_pairs": ["ETH/BTC","ADA/BTC"],
    "loglevel": "",
    "update_interval": 300,
    "selected_task": "default"
  },

  "database": {
    "engine": "sqlite",
    "host": "",
    "port": "",
    "db_name": "",
    "username": "",
    "password": ""
  },

  "exchanges": {
    "bittrex": {
      "required": {
        "enabled": true
      },
      "optional": {
        "key": "",
        "secret": ""
      }
    }
  },

  "notifiers": {
    "twilio": {
      "required": {
        "key": "",
        "secret": "",
        "sender_number": "",
        "receiver_number": ""
      }
    },
    "slack": {
      "required": {
        "key": "",
        "channel": ""
      }
    },
    "gmail": {
      "required": {
        "username": "",
        "password": "",
        "destination_emails": []
      }
    },
    "integram": {
      "required": {
        "url": ""
      }
    }
  },

  "behaviours": {
    "default": "",
    "rsi_bot": {
      "trade_parameters": {
        "mode": "simulate",
        "buy": {
          "btc_amount": 1,
          "btc_trade_limit": 0.1,
          "rsi_threshold": 75,
          "daily_volume_threshold": 0,
          "max_open_trades": 0
        },
        "sell": {
          "rsi_threshold": 25,
          "profit_margin_threshold": 0
        }
      }
    }
  }
}

**Comment by shads2** [comment]
Interesting, I'll look into this later today

**Comment by ejzwiers** [comment]
Found it. First the app/default-config.json file needs to be configured, next create the docker image: 
(run make build in the root of the project directory.). 
When running the app after the previous steps it seems to work!

**Comment by shads2** [comment]
Ah yes, I should update the doco to reflect that, I'm closing this for now :)
