### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by lucbas** [AbenezerMamo/crypto-signal#73]
Hi all

Great project!

I've cloned it to my Windows machine, installed requirements, configured `.env` (bittrex + integram) and `default-config.json` and when I try to run it locally, I'll get following error:

```
Traceback (most recent call last):
  File ".\app.py", line 12, in <module>
    from behaviour import Behaviour
  File "...\app\behaviour.py", line 5, in <module>
    from notification import Notifier
  File "...\app\notification.py", line 10, in <module>
    from notifiers.integram_client import IntegramNotifier
  File "...\app\notifiers\integram_client.py", line 2, in <module>
    import urllib.request
ImportError: No module named request
```

Thank you!

**Comment by jrbartola** [comment]
What version of python are you using? This project is built using Python 3.6; _urllib.request_ is only available on Python >= 3.3

**Comment by lucbas** [comment]
That's it, 2.7!

Thank you!

**Comment by jrbartola** [comment]
No problem :)
