### ISSUE TITLE
Help setting a symbol

### ISSUE THREAD

**Issue by Blackcol** [AbenezerMamo/crypto-signal#75]
I changed "market_pairs": [] at "default-config.json" to "market_pairs": ["BSD/BTC"] and a lot of combinations of symbols, with double q and without it, etc.. I can't get it working with just 1 symbol.. 
The error using the combination above:
Traceback (most recent call last):
  File "app.py", line 31, in <module>
    main()
  File "app.py", line 27, in main
    behaviour.run(settings['market_pairs'])
  File "/root/Downloads/crypto-signal-master/app/behaviours/default.py", line 16, in run
    market_data = self.exchange_interface.get_symbol_markets(market_pairs)
  File "/root/Downloads/crypto-signal-master/app/exchange.py", line 106, in get_symbol_markets
    market_pair]
KeyError: 'BSD/BTC'

**Comment by jrbartola** [comment]
Are you sure the exchange you've configured supports BSD wallets? I think you might be using Binance, and BSD/BTC trades are only available on Bittrex. Try swapping the configuration @Blackcol

**Comment by Blackcol** [comment]
working with python 3.6 idk why 2.7 isn't working, but is ok now, thanks =D

**Comment by shads2** [comment]
That's great! Thanks for letting us know.

It should work with python versions above 3.3 but the target version for development is 3.6. We don't at this stage plan to broaden the support as we do intend for it to be run via the docker container predominantly.
