### ISSUE TITLE
Feature Request: Add % price change at diferent timeframes

### ISSUE THREAD

**Issue by dhaern** [AbenezerMamo/crypto-signal#77]
Hi, my petition is scan % price variations at diferent timeframes (1m, 3m, 5m, 1h) on all coins/exchanges and send notifications to telegram group with all info and link to the exchange coin for example when a coin is going above or below this %. We could configure the +/- % and timeframe in the config files.

An example: http://www.cryptomarketscanner.com/

Thanks for all.

**Comment by shads2** [comment]
So the good news is Telegram is already supported as a notifier and at some point I had already planned to add a momentum based analyzer (that may replace the breakout analyzer).

The bad news is doing things with those time frames in the very near future is not probable, there is a significant amount of complexity in time frames as each exchange has a very different set of what they are willing to support for OHLCV data. And while I do plan to expand the config options available to the user there is a large problem with the config parser that needs solving before that happens.

**Comment by shads2** [comment]
I've implemented a momentum TA indicator in https://github.com/AbenezerMamo/crypto-signal/pull/164. At this stage I don't really have any plans to calculate price. We are keeping the project narrowly focused on being a TA assistant and while price changes are interesting... they are not really useful in a trade assistant sense.

So for now I am calling this feature implemented to the extent that I currently intend to implement it.

**Comment by shads2** [comment]
merged
