### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by zemelax** [AbenezerMamo/crypto-signal#8]
I kind of ran a bot, and he even in the console sends information about the coins. A couple of questions, how many coins does the bot analyze? We run the app.py file, and we do not touch the bittrex.py file, right? The program shows the pairs in the console window, is this correct? In advance, I apologize for the questions. I'm completely new to programming.

**Comment by AbenezerMamo** [comment]
You only need to change the json file and the app.py file. You can track as many coins as you want, just edit the array in app.py that holds the coin pairs to be tracked.
