### ISSUE TITLE
purely Binance user

### ISSUE THREAD

**Issue by riveryc** [AbenezerMamo/crypto-signal#82]
Hi, 

I'm a Binance user, don't have Bittrex account, and seems it's no longer open for register. 
Any chance or how to only use Binance API for this Application in .env file?
Also, what's is following?
TWILIO_REQUIRED_KEY=TWILIO_API_KEY
TWILIO_REQUIRED_SECRET=TWILIO_SECRET
TWILIO_REQUIRED_PHONE_NUMBER=TWILIO_PHONE_NUMBER
TWILIO_REQUIRED_MY_NUMBER=YOUR_PHONE_NUMBER

with GMAIL information, I've put in correct value, however, it returns me:
smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsw\n5.7.14 Zevx3WtOnX8Ak3dOIi-3yKnVE07SN5-GW8CtRhLEUh4jAeR5Xz8L8LaaqTQi61VFPUVbFx\n5.7.14 8q6XNQyzyIOb7qX8eHRTaCVRI0cOsDqOQH5R1HJ-bKIpcYNaA8Hq0cMI5EqO77S-WwHxUv\n5.7.14 7dRLFYEL4CPKB2IA0fTcHYdrFCYugKVZkzm43iz1OgHkVfK53L_WESKvE_RVJJQpemXk30\n5.7.14 OIv2H2Ewg2-D_ID59ZiGInARbOjcs> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 b8sm3600499pgt.14 - gsmtp')

Not too sure how to progress further. 

Thanks
River

**Comment by kfiresmith** [comment]
+1 to being able to toggle off exchanges.

**Comment by aneesv** [comment]
@riveryc @kfiresmith You can use .env to toggle exchanges.
To disable Bittrex ( Bittrex is enabled by default ) add `BITTREX_REQUIRE_ENABLED=false` to .env
To enable any exchange supported you can add
`<exchange>_REQUIRE_ENABLED=true` 
eg: `BINANCE_REQUIRE_ENABLED=true`
