### ISSUE TITLE
i'm noobs and uneducated ...

### ISSUE THREAD

**Issue by xonline** [AbenezerMamo/crypto-signal#85]
Hi guys, 

it took me a good 2 hours to install Docker Cloud on my Linux server. It is now running

Reading your second step.. 
"Next, to create the docker image run make build in the root of the project directory."

What? Where? how? 

Please help!

**Comment by jrbartola** [comment]
Navigate to the folder you downloaded crypto-signal to. In that directory, open up a terminal and type `make build`. This will build the docker image. Once that is completed, use `docker-compose run app` to run the program.

**Comment by shads2** [comment]
Hi xonline, it's also worth noting you don't need docker cloud to run this. You can just install the correct version of docker CE for your OS https://www.docker.com/community-edition#download as well as https://docs.docker.com/compose/install/. 

Having had the misfortune of managing a production Docker Cloud service before I would not recommend it, if you want a managed service try ECS with AWS or GKE with GCP. Alternatively I believe Heroku's free dyno tier may also support docker which would be the simplest non-self hosted option.

I would also recommend running `docker-compose run --rm app`

**Comment by Harut42** [comment]
Hello, 
i have installed the software 

(With Docker) Run docker-compose up in the root directory.
Now you're all set! Open up your favorite browser and navigate to http://localhost:5000/ and try it out.

the app start into ubuntu shell 👍 

Recreating cryptosignal_app_1 ... done
Attaching to cryptosignal_app_1
app_1  | BTC/USD:       Breakout: 0.0   RSI: 33.85      SMA: 5749.9266667       EMA: 5829.5214598       IMC: 13357.0000000/14488.0500000        MACD: -480.5613158
app_1  | IOTA/USD:      Breakout: 0.0   RSI: 37.84      SMA: 0.4284487  EMA: 0.4382754  IMC: 3.2854250/3.2848500        MACD: -0.0841567


While i try to connect to http://localhost:5000/  i have timeout, 

docker-proxy is running on port 5000 : 
root@ubuntu-minimal:/home/master/harut/crypto-signal# netstat -npl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1164/mysqld
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1069/sshd
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1224/postgres
tcp6       0      0 :::5000                 :::*                    LISTEN      9622/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      1421/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1069/sshd
tcp6       0      0 ::1:5432                :::*                    LISTEN      1224/postgres
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     SEQPACKET  LISTENING     267      449/systemd-udevd   /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     8734     1164/mysqld         /var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     543      1222/docker-contain /var/run/docker/containerd/docker-containerd-debug.sock
unix  2      [ ACC ]     STREAM     LISTENING     545      1222/docker-contain /var/run/docker/containerd/docker-containerd.sock
unix  2      [ ACC ]     STREAM     LISTENING     48107    9629/docker-contain @/containerd-shim/moby/b3efee51f31f4f51fc487c79c9b05eee760d4673e06d05939b68947efa7110f2/shim.sock
unix  2      [ ACC ]     STREAM     LISTENING     555      866/dockerd         /var/run/docker/metrics.sock
unix  2      [ ACC ]     STREAM     LISTENING     200      1/init              @/com/ubuntu/upstart
unix  2      [ ACC ]     STREAM     LISTENING     10600    1224/postgres       /var/run/postgresql/.s.PGSQL.5432
unix  2      [ ACC ]     STREAM     LISTENING     11894    866/dockerd         /run/docker/libnetwork/13a5a435aa220d5d5e761d8d460d6e6f6bc6e0788f6458986f1d2f58f4623e54.sock
unix  2      [ ACC ]     STREAM     LISTENING     397      950/dbus-daemon     /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     502      866/dockerd         /var/run/docker.sock


Please help!

**Comment by jrbartola** [comment]
You are still running the default behavior. Open the `default-config.json` file, and under the "settings" key change the value of "selected_task" from "default" to "server". Then run `docker-compose up` and try again.

**Comment by Harut42** [comment]
Is working, i can see WEBUI, 
btw i got error on clicking BEGIN button, any way to debug why ?

**Comment by jrbartola** [comment]
What does the error say?

**Comment by Harut42** [comment]
Uh oh!
Something went wrong: Response code 0. Please try again.

**Comment by jrbartola** [comment]
Response code 0 indicates that the server is not running. Make sure your console reports that the flask server is available at http://localhost:5000/ and there are no errors on that end either.

**Comment by Harut42** [comment]
Starting cryptosignal_app_1 ... done
Attaching to cryptosignal_app_1
app_1  |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
app_1  | 47.53.142.141 - - [19/Jan/2018 16:53:51] "GET / HTTP/1.1" 200 -

**Comment by jrbartola** [comment]
Okay, try filling out all the fields on the dashboard and try again. If the error still persists, could you tell me what the browser console says?

**Comment by Harut42** [comment]
error persist, 
in console i have only this output :
Starting cryptosignal_app_1 ... done
Attaching to cryptosignal_app_1
app_1  |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
app_1  | 47.53.142.141 - - [19/Jan/2018 16:53:51] "GET / HTTP/1.1" 200 -


app_1  | 47.53.142.141 - - [19/Jan/2018 16:58:49] "GET / HTTP/1.1" 200 -
app_1  | 47.53.142.141 - - [19/Jan/2018 16:59:22] "GET / HTTP/1.1" 200 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:09] "GET / HTTP/1.1" 200 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:09] "GET /static/css/botui.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:09] "GET /static/css/materialize.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:09] "GET /static/css/sweetalert2.min.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:09] "GET /static/js/sweetalert2.min.js HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:09] "GET /static/index.js HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:10] "GET / HTTP/1.1" 200 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:10] "GET /static/css/botui.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:11] "GET /static/css/materialize.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:11] "GET /static/css/sweetalert2.min.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:11] "GET /static/js/sweetalert2.min.js HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:02:11] "GET /static/index.js HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:54] "GET / HTTP/1.1" 200 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/css/botui.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/css/materialize.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/css/sweetalert2.min.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/js/sweetalert2.min.js HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/index.js HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET / HTTP/1.1" 200 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/css/botui.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/css/materialize.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/css/sweetalert2.min.css HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/js/sweetalert2.min.js HTTP/1.1" 304 -
app_1  | 47.53.142.141 - - [19/Jan/2018 17:07:55] "GET /static/index.js HTTP/1.1" 304 -
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by jrbartola** [comment]
What does the browser console say? Go to the website and press F12.

**Comment by Harut42** [comment]
TypeError: $(...).autocomplete is not a function
[Ulteriori informazioni]
index.js:24349:24
Object { currentprice: {…} }
 
Object { currentprice: {…} }

**Comment by jrbartola** [comment]
Ah, drat. I will get this fixed soon. Thanks!!

**Comment by mboncalo** [comment]
Hi,
How come, the trading bot is fetching data from Bittrex when I start it ? :)
I couldn't find the web interface conf, my bit is not listening on any port

**Comment by mboncalo** [comment]
Double checked, and it's connected to bittrex.com

**Comment by jrbartola** [comment]
By default it fetches data from Bittrex. You can change this in default-config.json.

**Comment by mboncalo** [comment]
What about the web interface ? Why is not binding to a port ? I understood that it has an UI

**Comment by mboncalo** [comment]
Also, it is possible to fetch only some specified BTC pairs info ? not scann for all of them
I tried to use "SETTINGS_MARKET_PAIRS=BTC/ETH,BTC/USDT" in the .env file, but I can't start the app afterwards:
Traceback (most recent call last):
  File "app.py", line 38, in <module>
    main()
  File "app.py", line 33, in main
    behaviour.run(settings['market_pairs'])
  File "/app/behaviours/default.py", line 39, in run
    market_data = self.exchange_interface.get_symbol_markets(market_pairs)
  File "/app/exchange.py", line 125, in get_symbol_markets
    market_pair]
KeyError: 'BTC/ETH'

BTC/ETH being the first pair in the list
Thanks.

**Comment by shads2** [comment]
The UI is only run if you run the app with "server" as the selected_task.

I think you will find the pair is listed on the exchange as ETH/BTC, the order is actually important :)

**Comment by shads2** [comment]
This conversation has become a bit unfocused, I am going to close this as it is no longer about anything in particular and new issues can be raised for specific problems.
