### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by GreenCame** [AbenezerMamo/crypto-signal#86]
Hello,

Great job, thanks !

I install docker and run crypto-signal on it. I use integram notification but I receive all these 4 notifications for EACH selected market pairs.

exemple with XMR/BTC
```
Horn
XMR/BTC is breaking out!
Horn
XMR/BTC is over bought!
Horn
XMR/BTC is trending well according to SMA!
Horn
XMR/BTC is trending well according to EMA!
```

but according to your log there 
`XMR/BTC:        Breakout: 0.0   RSI: 56.34      SMA: 0.0267194  EMA: 0.0271446 IMC: 0.0160291/0.0164874         MACD: 0.0017813`

I don't have breakout and over bought for exemple. Am I right ?

thanks ! have a good day

EDIT I clone the repo 48h ago maybe I will fetch it again :)

**Comment by shads2** [comment]
There is a fix in https://github.com/AbenezerMamo/crypto-signal/pull/80 that should put a stop to that kind of nonsense :)

**Comment by shads2** [comment]
Merged, it should no longer trigger alerts for thresholds that are not set. It will however still notify multiple times if multiple thresholds are crossed per coin. I will keep this open until that is also resolved.

**Comment by GreenCame** [comment]
cool, thanks ! :)

I did the rebase ! it's seem to work but selected market pairs doesn't... it fetch all market pair on bittrex now.

**Comment by shads2** [comment]
Oh, the configuration keys have changed slightly so that they are the full JSON path in the config file... so it's now SETTINGS_MARKET_PAIRS instead of just MARKET_PAIRS. This change was so that anything in the JSON config is also configurable via env var.

**Comment by GreenCame** [comment]
Yeah I saw that in code thanks :)

**Comment by shads2** [comment]
Fixed in https://github.com/AbenezerMamo/crypto-signal/pull/92

**Comment by GreenCame** [comment]
hi shads2 thanks for you job, maybe stupid but just a question about MACD I'm always notified about it but how can I do if I want notified about a signal crossed only ?

**Comment by shads2** [comment]
I might actually need to re-open this issue, I noticed this as a potential problem yesterday. Certain TA's are always by default above or below a threshold that would alert.

I'll need to add a feature to the config import to resolve this issue.

**Comment by jrbartola** [comment]
Done
