### ISSUE TITLE
LinkedIn won't let me message you!

### ISSUE THREAD

**Issue by danfinlay** [AbenezerMamo/crypto-signal#9]
Apparently without a pro account, LinkedIn won't let me friend request or message you.

This is Dan, from ConsenSys & MetaMask, we met at CalHacks on Friday night. I hope you had fun at the hackathon. Maybe you won?

Anyways, send me an email or something, so we have a communication channel. danfinlay@consensys.net

**Comment by AbenezerMamo** [comment]
Hey Dan! Tried sending you an email but it bounced. I added you on Linkedin and my email is Abe@Mamo.io

**Comment by danfinlay** [comment]
Got it! Thanks!
